{{- if .Values.webApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "init-wait-demo.serviceAccountName" . }}
  labels:
    {{- include "init-wait-demo.labels" . | nindent 4 }}
  {{- with .Values.webApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
