apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webApp.name }}
  labels:
    {{- include "init-wait-demo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.webApp.autoscaling.enabled }}
  replicas: {{ .Values.webApp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "init-wait-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webApp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "init-wait-demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.webApp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "init-wait-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webApp.podSecurityContext | nindent 8 }}
      initContainers:
      {{- range .Values.webApp.initContainers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .command }}
          command:
            {{- toYaml .command | nindent 12 }}
          {{- end }}
          resources: 
            {{- toYaml .resources | nindent 12 }}
          {{- if .environment }}
          env:
          {{- range .environment }}
          - name: {{ .name }}
          {{- if .configmap }}
            valueFrom:
              configMapKeyRef:
                name: {{ .configmap }}
                key: {{ .key }}
          {{- else if .secret }}
            valueFrom:
              secretKeyRef:
                name: {{ .secret }}
                key: {{ .key }}
          {{- else if .fieldRef }}
            valueFrom:
              fieldRef:
                fieldPath: {{ .fieldRef }}
          {{- else }}
            value: {{ .value }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.webApp.containerName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          ports:
          {{- range .Values.webApp.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.webApp.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.webApp.livenessProbe | omit .enabled | nindent 12 }}
          {{- end }}
          {{- if .Values.webApp.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.webApp.readinessProbe | omit .enabled | nindent 12 }}
          {{- end }}
          {{- if .Values.webApp.startupProbe.enabled }}
          startupProbe:
          {{- toYaml .Values.webApp.startupProbe | omit .enabled | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.webApp.resources | nindent 12 }}
          {{- if .Values.webApp.environment }}
          env:
          {{- range .Values.webApp.environment }}
          - name: {{ .name }}
          {{- if .configmap }}
            valueFrom:
              configMapKeyRef:
                name: {{ .configmap }}
                key: {{ .key }}
          {{- else if .secret }}
            valueFrom:
              secretKeyRef:
                name: {{ .secret }}
                key: {{ .key }}
          {{- else if .fieldRef }}
            valueFrom:
              fieldRef:
                fieldPath: {{ .fieldRef }}
          {{- else }}
            value: {{ .value }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.webApp.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.webApp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webApp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webApp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webApp.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
